2022-01-26 13:28:22,781 INFO    MainThread:11849 [wandb_setup.py:_flush():71] setting env: {}
2022-01-26 13:28:22,781 INFO    MainThread:11849 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-26 13:28:22,781 WARNING MainThread:11849 [wandb_setup.py:_flush():71] interrupted
Traceback (most recent call last):
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3251, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/tmp/ipykernel_11849/1919226361.py", line 1, in <module>
    trainer.train()
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/transformers/trainer.py", line 1275, in train
    self.control = self.callback_handler.on_train_begin(args, self.state, self.control)
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/transformers/trainer_callback.py", line 349, in on_train_begin
    return self.call_event("on_train_begin", args, state, control)
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/transformers/trainer_callback.py", line 390, in call_event
    result = getattr(callback, event)(
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/transformers/integrations.py", line 544, in on_train_begin
    self.setup(args, state, model, **kwargs)
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/transformers/integrations.py", line 517, in setup
    self._wandb.init(
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 953, in init
    raise e
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 928, in init
    wi.setup(kwargs)
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 181, in setup
    wandb_login._login(
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 274, in _login
    wlogin.prompt_api_key()
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 202, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 182, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 126, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 1026, in getpass
    return self._input_request(
  File "/home/donggunseo/anaconda3/envs/torch/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 1089, in _input_request
    raise KeyboardInterrupt("Interrupted by user") from None
KeyboardInterrupt: Interrupted by user
2022-01-26 13:28:22,784 INFO    MainThread:11849 [wandb_setup.py:_flush():71] setting login settings: {}
2022-01-26 13:28:22,784 INFO    MainThread:11849 [wandb_init.py:_log_setup():371] Logging user logs to /home/donggunseo/SCI-Kaggle/wandb/run-20220126_132822-9we6ggoz/logs/debug.log
2022-01-26 13:28:22,784 INFO    MainThread:11849 [wandb_init.py:_log_setup():372] Logging internal logs to /home/donggunseo/SCI-Kaggle/wandb/run-20220126_132822-9we6ggoz/logs/debug-internal.log
2022-01-26 13:28:22,784 INFO    MainThread:11849 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fda270c1d60>
2022-01-26 13:28:22,784 INFO    MainThread:11849 [wandb_init.py:init():404] calling init triggers
2022-01-26 13:28:22,784 INFO    MainThread:11849 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-01-26 13:28:22,784 INFO    MainThread:11849 [wandb_init.py:init():460] starting backend
2022-01-26 13:28:22,784 INFO    MainThread:11849 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-01-26 13:28:22,822 INFO    MainThread:11849 [backend.py:ensure_launched():216] starting backend process...
2022-01-26 13:28:22,860 INFO    MainThread:11849 [backend.py:ensure_launched():221] started backend process with pid: 13637
2022-01-26 13:28:22,861 INFO    MainThread:11849 [wandb_init.py:init():469] backend started and connected
2022-01-26 13:28:22,914 INFO    MainThread:11849 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-01-26 13:28:22,914 INFO    MainThread:11849 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-01-26 13:28:22,914 INFO    MainThread:11849 [wandb_init.py:init():533] updated telemetry
2022-01-26 13:28:23,004 INFO    MainThread:11849 [wandb_init.py:init():563] communicating current version
2022-01-26 13:28:24,182 INFO    MainThread:11849 [wandb_init.py:init():568] got version response 
2022-01-26 13:28:24,182 INFO    MainThread:11849 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-01-26 13:28:24,719 INFO    MainThread:11849 [wandb_init.py:init():606] starting run threads in backend
2022-01-26 13:28:26,570 INFO    MainThread:11849 [wandb_run.py:_console_start():1810] atexit reg
2022-01-26 13:28:26,570 INFO    MainThread:11849 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-01-26 13:28:26,570 INFO    MainThread:11849 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-01-26 13:28:26,572 INFO    MainThread:11849 [wandb_run.py:_redirect():1745] Redirects installed.
2022-01-26 13:28:26,572 INFO    MainThread:11849 [wandb_init.py:init():633] run started, returning control to user process
2022-01-26 13:28:26,574 INFO    MainThread:11849 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-26 13:28:26,574 INFO    MainThread:11849 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-01-26 13:28:35,566 INFO    MainThread:11849 [wandb_init.py:_resume_backend():293] resuming backend
2022-01-26 13:28:50,643 INFO    MainThread:11849 [wandb_init.py:_pause_backend():284] pausing backend
2022-01-26 13:28:50,643 INFO    MainThread:11849 [jupyter.py:save_ipynb():374] not saving jupyter notebook
